### ISSUE TITLE
BTC private key to address and balance check

### ISSUE THREAD

**Issue by Handsomekaizer** [Alvie/private-key-converter#3]
I just stumbled on these your GitHub repo I was looking for a program that will help me convert my compressed private key to address and check the balance. Could you please help me update or create a python program that will help me convert my compressed private key to address and check the balance. The reason I needed this was to scan through a massive private key txt file and see if I can find my missing 6 characters private key. Please help me if I recover the wallet I will donate some BTC to you. Thanks

**Comment by Alvie** [comment]
Sorry, I am only just seeing this GitHub issue now. This is beyond the scope of this web app and as a result I have to close this issue.

You can perhaps use https://github.com/pointbiz/bitaddress.org to get the address / public key related to the private key.
You can check the balance of an address perhaps with a blockchain explorer's API, or run a Bitcoin Insight (or similar) server locally.

Regarding the missing 6 characters, you may be able to brute force it with every combination.

I hope you found your BTC, if not then good luck, I hope you can find it.
